### ISSUE TITLE
Design issue with the Instagram icon

### ISSUE THREAD

**Issue by Amey-Chaudhari** [GLADIATRO/pet-adoption-platform#4]
there is some design issue with the Instagram icon in footer
![image](https://github.com/GLADIATRO/pet-adoption-platform/assets/64803502/85710f91-37af-49a1-802b-12f0eabdd5f7)
allow me to resolve it

**Comment by Amey-Chaudhari** [comment]
assign me the isssue

**Comment by Amey-Chaudhari** [comment]
check PR #5

**Comment by GLADIATRO** [comment]
ok
